name: Purge jsdelivr CDN
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    branches:
      - main
    paths:
      - "**.txt"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Purge jsdelivr CDN
        run: |
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref }}/${file}"
          done
